# ─────────────────────────────────────────────
# Selenium POM Framework — Configuration File
# Author: Prachi Dahibhate
# ─────────────────────────────────────────────

# Base URL
base.url=https://www.saucedemo.com

# Browser: chrome | firefox | edge
browser=chrome

# Run mode: local | remote
run.mode=local

# Remote Grid URL (only used when run.mode=remote)
grid.url=http://localhost:4444/wd/hub

# Timeouts (seconds)
implicit.wait=10
explicit.wait=15
page.load.timeout=30

# Test Data
test.data.path=src/test/resources/testdata/TestData.xlsx

# Screenshot on failure
screenshot.on.failure=true
screenshot.path=reports/screenshots/

# Extent Report
report.path=reports/ExtentReport.html
report.name=Selenium Automation Report
report.title=QA Automation Results — Prachi Dahibhate

# Headless mode (true | false)
headless=false

# Retry failed tests (0 = no retry)
retry.count=1
